{{- if and (.Values.kubecostModel.etlToDisk | default true)
           .Values.persistentVolume
           (not .Values.persistentVolume.dbExistingClaim)
           .Values.persistentVolume.enabled
           .Values.persistentVolume.dbPVEnabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "cost-analyzer.fullname" . }}-db
  labels:
    {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistentVolume.dbStorageClass }}
  storageClassName: {{ .Values.persistentVolume.dbStorageClass }}
  {{ end }}
  resources:
    requests:
    {{- if .Values.persistentVolume }}
      storage: {{ .Values.persistentVolume.dbSize }}
    {{- else }}
      storage: 32.0Gi
    {{ end }}
{{- end -}}
