{{- if and .Values.networkCosts
           .Values.networkCosts.enabled
           .Values.networkCosts.podSecurityPolicy
           .Values.networkCosts.podSecurityPolicy.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "cost-analyzer.fullname" . }}-network-costs
  labels:
    {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
  annotations:
{{- if .Values.networkCosts.podSecurityPolicy.annotations }}
{{ toYaml .Values.networkCosts.podSecurityPolicy.annotations | indent 4 }}
{{- end }}
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames:
  - {{ template "cost-analyzer.fullname" . }}-network-costs
{{- end }}
