annotations:
  artifacthub.io/links: |
    - name: Homepage
      url: https://www.kubecost.com
apiVersion: v2
appVersion: 1.96.0
dependencies:
- condition: global.grafana.enabled
  name: grafana
  repository: file://./charts/grafana
- condition: global.prometheus.enabled
  name: prometheus
  repository: file://./charts/prometheus
- condition: global.thanos.enabled
  name: thanos
  repository: file://./charts/thanos
description: A Helm chart that sets up Kubecost, Prometheus, and Grafana to monitor
  cloud costs.
name: cost-analyzer
version: 1.96.0
