kubecostDeployment:
  podSecurityContext:
# Note: Un-comment these securityContext configs for OCP cluster 4.11+
    # seccompProfile:
    #   type: RuntimeDefault
    runAsNonRoot: true
kubecostModel:
  etlCloudAsset: true # set to true to enable kubecost to include out-of-cluster cloud resources  (uses more memory)
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
# Note: Un-comment these securityContext configs for OCP cluster 4.11+
    # seccompProfile:
    #   type: RuntimeDefault
    capabilities:
      drop:
        - ALL
kubecostFrontend:
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
# Note: Un-comment these securityContext configs for OCP cluster 4.11+
    # seccompProfile:
    #   type: RuntimeDefault
    capabilities:
      drop:
        - ALL
kubecostNetworkCosts:
  securityContext: {}
  containerSecurityContext: {}

prometheus:
  server:
    containerSecurityContext:
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
# Note: Un-comment these securityContext configs for OCP cluster 4.11+
        # seccompProfile:
        #   type: RuntimeDefault
        capabilities:
          drop:
              - ALL
  sidecarContainers:
    containerSecurityContext:
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
# Note: Un-comment these securityContext configs for OCP cluster 4.11+
        # seccompProfile:
        #   type: RuntimeDefault
        capabilities:
          drop:
            - ALL
  configmapReload:
    containerSecurityContext:
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
# Note: Un-comment these securityContext configs for OCP cluster 4.11+
        # seccompProfile:
        #   type: RuntimeDefault
        capabilities:
          drop:
            - ALL
grafana:
  rbac:
    pspEnabled: false
  grafana:
    containerSecurityContext:
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
# Note: Un-comment these securityContext configs for OCP cluster 4.11+
        # seccompProfile:
        #   type: RuntimeDefault
        capabilities:
          drop:
            - ALL
  initContainers:
    containerSecurityContext:
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
# Note: Un-comment these securityContext configs for OCP cluster 4.11+
        # seccompProfile:
        #   type: RuntimeDefault
        capabilities:
          drop:
            - ALL
  sidecar:
    containerSecurityContext:
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
# Note: Un-comment these securityContext configs for OCP cluster 4.11+
        # seccompProfile:
        #   type: RuntimeDefault
        capabilities:
          drop:
            - ALL
thanos:
  thanosstore:
    containerSecurityContext:
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
# Note: Un-comment these securityContext configs for OCP cluster 4.11+
        # seccompProfile:
        #   type: RuntimeDefault
        capabilities:
          drop:
            - ALL
  thanosqueryfrontend:
    containerSecurityContext:
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
# Note: Un-comment these securityContext configs for OCP cluster 4.11+
        # seccompProfile:
        #   type: RuntimeDefault
        capabilities:
          drop:
            - ALL
  thanosquery:
    containerSecurityContext:
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
# Note: Un-comment these securityContext configs for OCP cluster 4.11+
        # seccompProfile:
        #   type: RuntimeDefault
        capabilities:
          drop:
            - ALL
  thanoscompact:
    containerSecurityContext:
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
# Note: Un-comment these securityContext configs for OCP cluster 4.11+
        # seccompProfile:
        #   type: RuntimeDefault
        capabilities:
          drop:
            - ALL