kubecostProductConfigs:
  clusterName: CLUSTER_NAME
  # projectID: CLUSTER_NAME

prometheus:
  nodeExporter:
    enabled: false
  serviceAccounts:
    nodeExporter:
      create: false
  kube-state-metrics:
    disabled: true
  server:
    global:
      external_labels:
        cluster_id: CLUSTER_NAME
networkCosts:
  enabled: false
