ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: gce
    external-dns.alpha.kubernetes.io/hostname: kubecost.mgmt.csp01.saas.broadcom.com
  paths:
  - backend:
      serviceName: kubecost-cost-analyzer
      servicePort: 9090
    path: /
  hosts:
    - kubecost.mgmt.csp01.saas.broadcom.com
  tls:
    - secretName: cost-analyzer-tls
      hosts:
        - kubecost.mgmt.csp01.saas.broadcom.com