kubecostDeployment:
  podSecurityContext: {}
kubecostModel:
  containerSecurityContext: {}
kubecostFrontend:
  containerSecurityContext: {}
kubecostNetworkCosts:
  podSecurityContext: {}
  containerSecurityContext: {}
prometheus:
  server:
    containerSecurityContext:
      securityContext: {}
  sidecarContainers:
    containerSecurityContext:
      securityContext: {}
  configmapReload:
    containerSecurityContext:
      securityContext: {}
grafana:
  grafana:
    containerSecurityContext:
      securityContext: {}
  initContainers:
    containerSecurityContext:
      securityContext: {}
  sidecar:
    containerSecurityContext:
      securityContext: {}
thanos:
  thanosstore:
    containerSecurityContext:
      securityContext: {}
  thanosqueryfrontend:
    containerSecurityContext:
      securityContext: {}
  thanosquery:
    containerSecurityContext:
      securityContext: {}
  thanoscompact:
    containerSecurityContext:
      securityContext: {}